#!/bin/bash
mkdir -p ~/.vim
mkdir -p ~/.local/bin
mkdir -p ~/.local/share
ln -sf ~/waydots/.vimrc ~/
ln -sf ~/waydots/.vim/autoload ~/.vim/
ln -sf ~/waydots/.bashrc ~/
ln -sf ~/waydots/.config/sway ~/.config/
ln -sf ~/waydots/.config/dunst ~/.config/
ln -sf ~/waydots/.config/foot ~/.config/
ln -sf ~/waydots/.config/fish ~/.config/
ln -sf ~/waydots/.config/tofi ~/.config/
ln -sf ~/waydots/.config/starship.toml ~/.config/
ln -sf ~/waydots/.local/bin ~/.local/
ln -sf ~/waydots/.local/share/fonts ~/.local/share/
ln -sf ~/waydots/.local/share/icons ~/.local/share/
ln -sf ~/waydots/.local/share/pokemon-colorscripts ~/.local/share/
ln -sf ~/waydots/.themes ~/
ln -sf ~/waydots/.icons ~/
